### ISSUE TITLE
Non riesco ad entrare nell'admin

### ISSUE THREAD

**Issue by LaScuolaDelleArti** [jiabin/jiabin.github.io#1]
In home page http://www.lascuoladellearti.it/ cliccando su EVENTI a destra non va.
Il tutto è nato perché ho cancellato una NEWS dall'admin. Non riesco infatti ad accedere all'admin con nessun user, mi da errore 504.

**Comment by aaaakille** [comment]
stiamo cercando l'id mancante

**Comment by LaScuolaDelleArti** [comment]
Se può aiutarvi ho cancellato una news che si chiamava "La morte balla sui tacchi a spillo" datato 27 gennaio.

**Comment by LaScuolaDelleArti** [comment]
Buongiorno! Ora funziona tutto ma nella pagina degli eventi http://www.lascuoladellearti.it/pages/gli-eventi in alto in alto anziché il titolo della pagina si legge TEST.

**Comment by LaScuolaDelleArti** [comment]
Ho risolto io.

**Comment by aaaakille** [comment]
sì bastava cambiare il titolo giusto?
