### ISSUE TITLE
Newsletter non funziona

### ISSUE THREAD

**Issue by LaScuolaDelleArti** [jiabin/jiabin.github.io#4]
Buongiorno! Devo mandare entro oggi una newsletter ma dopo che clicco su Play continua a dirmi WAITING.
Potete aiutarmi?
http://www.lascuoladellearti.it/admin/julius/newsletter/newsletter/list

**Comment by eymengunay** [comment]
Buongiorno,

Uno dei nostri server di posta era giu'. Abbiamo riavviato, adesso funziona correttamente

**Comment by eymengunay** [comment]
C'erano 5 newsletter col stato "WAITING". Sono partite tutte:
http://www.lascuoladellearti.it/admin/julius/newsletter/dispatch/54fd7da23f3092aa4c8b45ab/show
http://www.lascuoladellearti.it/admin/julius/newsletter/dispatch/54fd7eb03f3092aa4c8b45ac/show
http://www.lascuoladellearti.it/admin/julius/newsletter/dispatch/54fd7fda3f3092ac4c8b45c6/show
http://www.lascuoladellearti.it/admin/julius/newsletter/dispatch/54fd80383f3092cc488b45fc/show
http://www.lascuoladellearti.it/admin/julius/newsletter/dispatch/54fd81b53f309208278b4694/show

**Comment by LaScuolaDelleArti** [comment]
Grazie mille!!
